const fs = require('fs');
const path = require('path');

const content = [
  "'use client';",
  "",
  "import React, { useState, useRef, useCallback, useEffect } from 'react';",
  "",
  "interface ClarificationOption {",
  "  id: string;",
  "  label: string;",
  "  recommended?: boolean;",
  "}",
  "",
  "interface ClarificationCardProps {",
  "  question: string;",
  "  options: ClarificationOption[];",
  "  allowMultiple?: boolean;",
  "  onSend?: (content: string) => void;",
  "}",
  "",
  "export function ClarificationCard({ question, options, onSend }: ClarificationCardProps) {",
  "  const [focusedIndex, setFocusedIndex] = useState(-1);",
  "  const [selectedId, setSelectedId] = useState<string | null>(null);",
  "  const buttonRefs = useRef<(HTMLButtonElement | null)[]>([]);",
  "  const containerRef = useRef<HTMLDivElement>(null);",
  "",
  "  useEffect(() => {",
  "    buttonRefs.current = buttonRefs.current.slice(0, options.length);",
  "  }, [options.length]);",
  "",
  "  useEffect(() => {",
  "    if (focusedIndex >= 0 && focusedIndex < options.length) {",
  "      buttonRefs.current[focusedIndex]?.focus();",
  "    }",
  "  }, [focusedIndex, options.length]);",
  "",
  "  const handleSelect = useCallback((option: ClarificationOption) => {",
  "    setSelectedId(option.id);",
  "    setTimeout(() => {",
  "      onSend?.(option.label);",
  "    }, 150);",
  "  }, [onSend]);",
  "",
  "  const handleKeyDown = useCallback(",
  "    (e: React.KeyboardEvent<HTMLDivElement>) => {",
  "      const count = options.length;",
  "      if (count === 0) return;",
  "",
  "      switch (e.key) {",
  "        case 'ArrowDown':",
  "        case 'ArrowRight': {",
  "          e.preventDefault();",
  "          setFocusedIndex((prev) => (prev + 1) % count);",
  "          break;",
  "        }",
  "        case 'ArrowUp':",
  "        case 'ArrowLeft': {",
  "          e.preventDefault();",
  "          setFocusedIndex((prev) => (prev - 1 + count) % count);",
  "          break;",
  "        }",
  "        case 'Enter':",
  "        case ' ': {",
  "          if (focusedIndex >= 0 && focusedIndex < count) {",
  "            e.preventDefault();",
  "            handleSelect(options[focusedIndex]);",
  "          }",
  "          break;",
  "        }",
  "        default: {",
  "          const num = parseInt(e.key, 10);",
  "          if (num >= 1 && num <= count) {",
  "            e.preventDefault();",
  "            handleSelect(options[num - 1]);",
  "          }",
  "          break;",
  "        }",
  "      }",
  "    },",
  "    [options, focusedIndex, handleSelect],",
  "  );",
  "",
  "  const setButtonRef = useCallback(",
  "    (index: number) => (el: HTMLButtonElement | null) => {",
  "      buttonRefs.current[index] = el;",
  "    },",
  "    [],",
  "  );",
  "",
  "  if (options.length === 0) return null;",
  "",
  "  const questionIcon = (",
  "    <svg",
  '      className="h-3.5 w-3.5 text-amber-500 shrink-0"',
  '      viewBox="0 0 24 24"',
  '      fill="none"',
  '      stroke="currentColor"',
  '      strokeWidth="2"',
  '      strokeLinecap="round"',
  '      strokeLinejoin="round"',
  "    >",
  '      <circle cx="12" cy="12" r="10" />',
  '      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />',
  '      <line x1="12" y1="17" x2="12.01" y2="17" />',
  "    </svg>",
  "  );",
  "",
  "  const starIcon = (",
  '    <svg className="h-2 w-2" viewBox="0 0 24 24" fill="currentColor">',
  '      <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />',
  "    </svg>",
  "  );",
  "",
  "  const checkIcon = (",
  "    <svg",
  '      className="flex-shrink-0 h-3.5 w-3.5 text-sky-500 mt-0.5"',
  '      viewBox="0 0 24 24"',
  '      fill="none"',
  '      stroke="currentColor"',
  '      strokeWidth="3"',
  '      strokeLinecap="round"',
  '      strokeLinejoin="round"',
  "    >",
  '      <polyline points="20 6 9 17 4 12" />',
  "    </svg>",
  "  );",
  "",
  "  return (",
  "    <div",
  "      ref={containerRef}",
  '      className="my-2 rounded-lg border ide-border ide-surface-inset overflow-hidden"',
  '      role="listbox"',
  '      aria-label="Clarification options"',
  '      aria-live="polite"',
  "      tabIndex={0}",
  "      onKeyDown={handleKeyDown}",
  "      onFocus={() => {",
  "        if (focusedIndex < 0) setFocusedIndex(0);",
  "      }}",
  "      onBlur={(e) => {",
  "        if (!containerRef.current?.contains(e.relatedTarget as Node)) {",
  "          setFocusedIndex(-1);",
  "        }",
  "      }}",
  "    >",
  '      <div className="px-3 py-2 border-b ide-border-subtle">',
  '        <div className="flex items-center gap-1.5">',
  "          {questionIcon}",
  '          <p className="text-xs ide-text-1 font-medium">{question}</p>',
  "        </div>",
  "      </div>",
  "",
  '      <div className="p-1.5 flex flex-col gap-1">',
  "        {options.map((option, i) => {",
  "          const isRecommended = option.recommended === true;",
  "          const isSelected = selectedId === option.id;",
  "          const isFocused = focusedIndex === i;",
  "",
  "          const base =",
  "            'relative flex items-start gap-2 w-full text-left text-xs rounded-md px-3 py-2 transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500/60 disabled:opacity-60 disabled:cursor-default';",
  "",
  "          let state: string;",
  "          if (isSelected) {",
  "            state = 'bg-sky-500/15 border border-sky-500/40 text-sky-600 dark:text-sky-300';",
  "          } else if (isRecommended) {",
  "            state =",
  "              'bg-emerald-500/5 border border-emerald-500/25 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-500/10 hover:border-emerald-500/40';",
  "          } else {",
  "            state =",
  "              'ide-surface hover:ide-surface-input border ide-border-subtle ide-text-2 hover:ide-text';",
  "          }",
  "",
  "          const numStyle = isRecommended",
  "            ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-300'",
  "            : 'ide-surface-inset ide-text-3';",
  "",
  "          return (",
  "            <button",
  "              key={option.id}",
  "              ref={setButtonRef(i)}",
  '              type="button"',
  '              role="option"',
  "              aria-selected={isFocused}",
  "              tabIndex={isFocused ? 0 : -1}",
  "              onClick={() => handleSelect(option)}",
  "              disabled={selectedId !== null}",
  "              className={`${base} ${state}`}",
  "            >",
  "              <span",
  "                className={`flex-shrink-0 w-4 h-4 rounded flex items-center justify-center text-[10px] font-semibold mt-0.5 ${numStyle}`}",
  "              >",
  "                {i + 1}",
  "              </span>",
  "",
  '              <span className="flex-1 leading-relaxed">{option.label}</span>',
  "",
  "              {isRecommended && !isSelected && (",
  '                <span className="flex-shrink-0 inline-flex items-center gap-0.5 rounded-full bg-emerald-500/15 px-1.5 py-0.5 text-[9px] font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider mt-0.5">',
  "                  {starIcon}",
  "                  Best",
  "                </span>",
  "              )}",
  "",
  "              {isSelected && checkIcon}",
  "            </button>",
  "          );",
  "        })}",
  "      </div>",
  "",
  '      <div className="px-3 py-1.5 border-t ide-border-subtle">',
  '        <p className="text-[10px] ide-text-quiet">',
  "          {'Press '}",
  '          <kbd className="px-1 py-0.5 rounded ide-surface-inset ide-border text-[9px] font-mono">1</kbd>',
  "          {'-'}",
  '          <kbd className="px-1 py-0.5 rounded ide-surface-inset ide-border text-[9px] font-mono">{options.length}</kbd>',
  "          {' or click to select'}",
  "        </p>",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
].join('\n');

fs.writeFileSync(
  path.join(__dirname, 'components', 'ai-sidebar', 'ClarificationCard.tsx'),
  content
);
console.log('ClarificationCard.tsx written successfully');
