const fs = require('fs');
const path = require('path');

const lines = [];
lines.push('---');
lines.push('description: Systematic methodology for searching Shopify theme file trees, diagnosing display bugs, and resolving issues efficiently. Apply when debugging theme issues or investigating why something is not rendering correctly.');
lines.push('alwaysApply: true');
lines.push('---');
lines.push('');
lines.push('# Theme File Search and Debugging Methodology');
lines.push('');
lines.push('## 1. Start From Intent, Not Filenames');
lines.push('');
lines.push('When the user describes a problem, translate their intent into the rendering chain BEFORE searching.');
lines.push('');
lines.push('- "product image not showing" -> What renders a product image? -> templates/product*.json -> sections/main-product*.liquid -> snippets/product-thumbnail*.liquid -> assets/lazysizes*.js');
lines.push('- "header menu broken" -> What renders the header? -> layout/theme.liquid -> sections/header*.liquid -> snippets/menu-*.liquid -> assets/header*.js');
lines.push('- "cart not updating" -> What handles cart? -> templates/cart*.json -> sections/main-cart*.liquid -> assets/cart*.js');
lines.push('- "page loading slow" -> What loads on every page? -> layout/theme.liquid -> assets/*.js (check sizes) -> config/settings_data.json');
lines.push('');
lines.push('Rule: Never grep for a single keyword and call it done. Always trace the full rendering chain.');
lines.push('');
lines.push('## 2. Multi-Strategy Search (Parallel)');
lines.push('');
lines.push('Fire multiple search strategies at once. Do not wait for one to fail before trying another:');
lines.push('');
lines.push('1. **Glob** for file name patterns: `*product*`, `*thumbnail*`, `*gallery*`');
lines.push('2. **Grep** for code patterns: `image_url`, `lazyload`, `opacity:0`, `display:none`');
lines.push('3. **Reference trace**: Read a file -> find its render/include/asset_url calls -> follow those');
lines.push('4. **Semantic search**: "where are product images rendered" (concept-level, not keyword)');
lines.push('');
lines.push('Rule: Use at least 2 strategies for every investigation. If using only grep, you are doing it wrong.');
lines.push('');
lines.push('## 3. The Rendering Chain (Shopify Themes)');
lines.push('');
lines.push('Every page renders through this chain. Trace downward to find code, upward to find the cause:');
lines.push('');
lines.push('```');
lines.push('layout/theme.liquid            <- Global: head, body, scripts, CSS');
lines.push('  templates/<page>.json        <- Declares which sections render (NOT rendering code)');
lines.push('    sections/<type>.liquid     <- Actual HTML + Liquid rendering + schema');
lines.push('      snippets/<name>.liquid   <- Reusable partials via render tag');
lines.push('        assets/<name>.js|css   <- Behavior + styling');
lines.push('```');
lines.push('');
lines.push('Common misconceptions to avoid:');
lines.push('- The template JSON does NOT contain rendering logic. It only declares section order.');
lines.push('- `sections/main-product.liquid` is a SECTION, not a template.');
lines.push('- Snippets often contain the actual markup (images, cards, prices).');
lines.push('- JavaScript in `assets/` frequently controls visibility (lazy-loading, sliders, animations).');
lines.push('');
lines.push('## 4. Form Multiple Hypotheses');
lines.push('');
lines.push('For any "X is not showing" or "X looks wrong" issue, immediately consider ALL of these:');
lines.push('');
lines.push('- **Liquid rendering**: Is content output at all? Check conditional logic, variable assignment, if blocks.');
lines.push('- **CSS visibility**: Is it rendered but hidden? Check `opacity:0`, `display:none`, `visibility:hidden`, `height:0`, `overflow:hidden`.');
lines.push('- **JS interference**: Is JS hiding or removing it? Check lazy-load failures, slider init errors, DOM manipulation.');
lines.push('- **Asset loading**: Is a required file failing? Check for 404 errors, CORS blocks, parse errors in minified JS.');
lines.push('- **Specificity conflicts**: Is another rule overriding? Check `!important`, inline styles, JS-injected styles.');
lines.push('');
lines.push('Rule: Never fixate on one hypothesis. Check at least 2-3 before proposing a fix.');
lines.push('');
lines.push('## 5. The Escalation Ladder');
lines.push('');
lines.push('When the obvious file does not have the answer, widen systematically:');
lines.push('');
lines.push('1. Check the **snippet** -- actual markup is often one level deeper than expected');
lines.push('2. Check **JavaScript assets** -- lazy-loaders, sliders, jQuery plugins control visibility');
lines.push('3. Check **CSS assets** -- search for the element class names in all CSS files');
lines.push('4. Check **layout/theme.liquid** -- global scripts, preloaders, body class injection');
lines.push('5. Check **config/settings_data.json** -- theme settings that toggle features on/off');
lines.push('6. Check for **third-party interference** -- app scripts, external CDN scripts, jQuery conflicts');
lines.push('7. Ask for **browser diagnostics** -- console errors, computed styles, DOM inspector output');
lines.push('');
lines.push('Rule: Never say "I cannot find it." Instead say "I have checked X, Y, Z. The issue is not there. I need to see [specific file] because [reason]."');
lines.push('');
lines.push('## 6. Cross-File Awareness');
lines.push('');
lines.push('The bug is rarely in the file the user expects. Common patterns:');
lines.push('');
lines.push('- Image not showing? -> Check the JS lazy-loader, not just the Liquid template.');
lines.push('- Layout broken? -> Check the CSS asset, not just the section HTML.');
lines.push('- Content flickering? -> Check JS that manipulates display/opacity after page load.');
lines.push('- Style not applying? -> Check specificity: inline styles > ID > class > element. Also check `!important`.');
lines.push('- Feature not working on one template? -> Check `template.suffix` conditionals in layout/theme.liquid.');
lines.push('');
lines.push('## 7. Confidence Gating');
lines.push('');
lines.push('Before proposing a fix, assess confidence:');
lines.push('');
lines.push('- **HIGH** (above 80%): Can see the exact problematic line. Propose the fix directly.');
lines.push('- **MEDIUM** (40-80%): Likely cause found but alternatives exist. Propose fix AND mention other possibilities.');
lines.push('- **LOW** (below 40%): Not enough context. DO NOT GUESS. List what files you need and why.');
lines.push('');
lines.push('## 8. When the First Fix Does Not Work');
lines.push('');
lines.push('DO NOT repeat the same approach. Escalate:');
lines.push('');
lines.push('1. Re-read affected files looking for patterns you missed (especially JS running on page load)');
lines.push('2. Search for the element CSS classes across ALL asset files (not just the obvious one)');
lines.push('3. Check for `!important` rules, inline styles, or JS-injected styles that override your fix');
lines.push('4. Look at `layout/theme.liquid` for global scripts that might interfere');
lines.push('5. Consider third-party scripts (theme apps, external libraries)');
lines.push('6. Ask the user for: browser console output, computed styles from inspector, or DOM tree screenshot');
lines.push('');
lines.push('Rule: If you have tried the same type of fix twice and it has not worked, the problem is in a different file than you think. Widen your search.');
lines.push('');
lines.push('## 9. Third-Party Theme Patterns');
lines.push('');
lines.push('Many Shopify themes deviate from Dawn conventions. Watch for:');
lines.push('');
lines.push('- **Custom lazy-loading**: lazySizesT4, lozad, custom IntersectionObservers in `assets/lazysizes*.js`');
lines.push('- **Slider libraries**: Slick, Flickity, Swiper, Glide in `assets/slick*.js`, `assets/flickity*.js`');
lines.push('- **jQuery dependency**: Many themes load jQuery. Check `layout/theme.liquid` for script tags.');
lines.push('- **CSS class prefixes**: `t4s-`, `tt-`, `nt-`, `tc-`. Search for the prefix pattern in assets.');
lines.push('- **Opacity/visibility patterns**: Themes hide content with `opacity:0` and reveal via JS class toggle.');
lines.push('- **Template suffixes**: `template.suffix` controls which variant of a page renders. Check body class.');
lines.push('');
lines.push('## 10. Verification Protocol');
lines.push('');
lines.push('After making a fix:');
lines.push('1. Trace the rendering chain again to verify the fix hits the right place');
lines.push('2. Check if other files reference the same element/class and might conflict');
lines.push('3. Consider edge cases: different templates, mobile vs desktop, with/without JS');
lines.push('4. If the fix is in JS, check that the script actually loads on the affected page');
lines.push('5. If the fix is in CSS, check specificity against existing rules');
lines.push('');

fs.writeFileSync(
  path.join(__dirname, '.cursor', 'rules', 'theme-debugging.mdc'),
  lines.join('\n')
);
console.log('Written successfully:', lines.length, 'lines');
