import type { MockOrderContext } from './types';

const SHOP_ADDRESS = {
  name: 'Sample Store',
  first_name: 'Sample',
  last_name: 'Store',
  company: 'Sample Store LLC',
  address1: '150 Elgin Street',
  address2: 'Suite 800',
  city: 'Ottawa',
  province: 'Ontario',
  province_code: 'ON',
  country: 'Canada',
  country_code: 'CA',
  zip: 'K2P 1L4',
  phone: '+1 (613) 555-0199',
};

const SHIPPING_ADDRESS = {
  name: 'Jane Smith',
  first_name: 'Jane',
  last_name: 'Smith',
  company: '',
  address1: '123 Main Street',
  address2: 'Apt 4B',
  city: 'Toronto',
  province: 'Ontario',
  province_code: 'ON',
  country: 'Canada',
  country_code: 'CA',
  zip: 'M5V 2T6',
  phone: '+1 (416) 555-0123',
};

const BILLING_ADDRESS = {
  name: 'Jane Smith',
  first_name: 'Jane',
  last_name: 'Smith',
  company: '',
  address1: '123 Main Street',
  address2: 'Apt 4B',
  city: 'Toronto',
  province: 'Ontario',
  province_code: 'ON',
  country: 'Canada',
  country_code: 'CA',
  zip: 'M5V 2T6',
  phone: '+1 (416) 555-0123',
};

const LINE_ITEMS = [
  {
    title: 'Classic Cotton T-Shirt',
    variant_title: 'Medium / Navy',
    sku: 'TSH-NAV-M',
    quantity: 2,
    price: '29.99',
    final_price: '29.99',
    final_line_price: '59.98',
    grams: 200,
    image: 'https://placehold.co/120x120/e2e8f0/475569?text=T-Shirt',
    requires_shipping: true,
    product: {
      title: 'Classic Cotton T-Shirt',
      type: 'Apparel',
      vendor: 'Sample Brand',
    },
    fulfillment: {
      tracking_number: '1Z999AA10123456784',
      tracking_company: 'UPS',
      tracking_url: 'https://www.ups.com/track?tracknum=1Z999AA10123456784',
      created_at: '2026-02-25T10:30:00Z',
      status: 'in_transit',
    },
  },
  {
    title: 'Organic Tote Bag',
    variant_title: 'Natural',
    sku: 'BAG-NAT-OS',
    quantity: 1,
    price: '18.50',
    final_price: '18.50',
    final_line_price: '18.50',
    grams: 350,
    image: 'https://placehold.co/120x120/e2e8f0/475569?text=Tote+Bag',
    requires_shipping: true,
    product: {
      title: 'Organic Tote Bag',
      type: 'Accessories',
      vendor: 'Sample Brand',
    },
    fulfillment: null,
  },
  {
    title: 'Stainless Steel Water Bottle',
    variant_title: '750ml / Matte Black',
    sku: 'BTL-BLK-750',
    quantity: 1,
    price: '34.00',
    final_price: '34.00',
    final_line_price: '34.00',
    grams: 420,
    image: 'https://placehold.co/120x120/e2e8f0/475569?text=Bottle',
    requires_shipping: true,
    product: {
      title: 'Stainless Steel Water Bottle',
      type: 'Drinkware',
      vendor: 'Sample Brand',
    },
    fulfillment: {
      tracking_number: '1Z999AA10123456784',
      tracking_company: 'UPS',
      tracking_url: 'https://www.ups.com/track?tracknum=1Z999AA10123456784',
      created_at: '2026-02-25T10:30:00Z',
      status: 'in_transit',
    },
  },
];

export const MOCK_ORDER_CONTEXT: MockOrderContext = {
  order: {
    id: 4567890123,
    name: '#1042',
    order_number: 1042,
    email: 'jane.smith@example.com',
    created_at: '2026-02-24T14:22:00Z',
    financial_status: 'paid',
    fulfillment_status: 'partial',
    total_price: '122.07',
    subtotal_price: '112.48',
    total_tax: '14.62',
    total_discounts: '5.03',
    shipping_price: '0.00',
    note: 'Please include a gift receipt. Thank you!',
    cancelled: false,
    cancel_reason: null,
    line_items: LINE_ITEMS,
    shipping_address: SHIPPING_ADDRESS,
    billing_address: BILLING_ADDRESS,
    customer: {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      first_name: 'Jane',
      last_name: 'Smith',
      phone: '+1 (416) 555-0123',
    },
  },
  line_items: LINE_ITEMS,
  shipping_address: SHIPPING_ADDRESS,
  billing_address: BILLING_ADDRESS,
  shop: {
    name: 'Sample Store',
    email: 'hello@samplestore.com',
    domain: 'samplestore.myshopify.com',
    url: 'https://samplestore.myshopify.com',
    currency: 'CAD',
    money_format: '${{amount}}',
    address: SHOP_ADDRESS,
  },
  shop_address: SHOP_ADDRESS,
  customer: {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    first_name: 'Jane',
    last_name: 'Smith',
    phone: '+1 (416) 555-0123',
  },
};
