/**
 * Knowledge module: WCAG accessibility patterns for Shopify e-commerce themes.
 * Covers contrast, focus, ARIA, semantic HTML, motion, and e-commerce specifics.
 */

export const A11Y_PATTERNS = [
  '## Accessibility Patterns for E-Commerce',
  '',
  '### WCAG AA Contrast Requirements',
  '- Normal text: 4.5:1 contrast ratio minimum',
  '- Large text (18px+ or 14px+ bold): 3:1 contrast ratio minimum',
  '- Use color_contrast filter in Liquid to validate dynamically',
  '- Test with both light and dark theme settings',
  '- Sale/discount badges often fail -- red on white needs checking',
  '',
  '### Image Accessibility',
  '- Every img tag must have alt attribute',
  '- Product images: alt with image.alt escaped, fallback to product title',
  '- Decorative images: alt="" (empty, not omitted)',
  '- Background images with text overlay: use aria-label on container',
  '- SVG icons: role="img" with aria-label, or aria-hidden="true" if decorative',
  '',
  '### Form Accessibility',
  '- Every input needs associated label (for/id match) or aria-label',
  '- Quantity inputs: aria-label with product title for context',
  '- Search inputs: label + role="search" on form',
  '- Error messages: aria-live="polite" for dynamic validation',
  '- Required fields: aria-required="true" and visible indicator',
  '- Group related fields with fieldset and legend',
  '',
  '### Semantic HTML',
  '- Use header, nav, main, section, article, footer appropriately',
  '- One main element per page',
  '- nav for primary/secondary navigation with aria-label to distinguish',
  '- section with aria-labelledby for distinct page regions',
  '- Use button for actions, a for navigation -- never div/span for interactive',
  '',
  '### Focus Management',
  '- Visible focus styles: :focus-visible with outline or box-shadow',
  '- Focus ring: 2px minimum, high contrast against background',
  '- Modal/drawer: trap focus inside, return focus on close',
  '- Skip link: first focusable element, targets main content',
  '- Tab order must follow visual order (avoid tabindex > 0)',
  '',
  '### Motion and Animation',
  '- Wrap animations in @media (prefers-reduced-motion: no-preference)',
  '- Carousels: pause on hover/focus, provide prev/next controls',
  '- Auto-playing video: must have pause control',
  '- Slide-in drawers: respect reduced motion preference',
  '',
  '### ARIA for E-Commerce',
  '- Cart count: aria-live="polite" to announce updates',
  '- Add to cart button: aria-label with product name for context',
  '- Variant swatches: role="radiogroup" with role="radio" children',
  '- Price: use aria-label for screen reader friendly format',
  '- Sale price: visually-hidden text "Original price" / "Sale price"',
  '- Filters: aria-expanded on toggle, aria-controls on panel',
  '- Pagination: nav with aria-label="Pagination"',
  '- Sort dropdown: aria-label="Sort by"',
  '',
  '### Keyboard Navigation',
  '- All interactive elements reachable via Tab',
  '- Escape closes modals, drawers, and popups',
  '- Arrow keys for option selectors, sliders, tabs',
  '- Enter/Space activates buttons and links',
  '- Mega menus: arrow key navigation between items',
  '',
  '### Touch Targets',
  '- Minimum 44x44px touch target size (WCAG 2.5.5)',
  '- Adequate spacing between adjacent targets (8px+)',
  '- Swatches and size selectors must meet minimum size',
].join('\\n');

export const A11Y_PATTERNS_KEYWORDS = [
  'accessibility', 'a11y', 'wcag', 'aria', 'alt', 'contrast',
  'focus', 'keyboard', 'screen reader', 'label', 'semantic',
  'role', 'tab', 'tabindex', 'skip link', 'reduced motion',
  'prefers-reduced-motion', 'aria-live', 'aria-label',
  'aria-expanded', 'aria-hidden', 'aria-describedby',
  'focus-visible', 'outline', 'touch target',
  'fieldset', 'legend', 'visually-hidden',
];

export const A11Y_PATTERNS_TOKENS = 1400;
