/**
 * Knowledge module: CSS architecture, JavaScript patterns, BEM naming,
 * Dawn conventions, and design tokens for Shopify themes.
 * Consolidates CSS_ARCHITECTURE, JS_PATTERNS, DAWN_CONVENTIONS from shopify-best-practices.
 */

export const CSS_JS_STANDARDS = [
  '## CSS and JavaScript Standards for Shopify Themes',
  '',
  '### CSS Architecture',
  '- Specificity ceiling: target 0-1-0 (single class) for most selectors. Max 0-4-0 for parent-child.',
  '- Never use IDs as selectors. No !important unless documented why.',
  '- CSS variables: never hardcode colors or magic numbers. Define variables first.',
  '- Global variables: define in :root in snippets/theme-styles-variables.liquid',
  '- Scoped variables can reference globals and be overridden per component.',
  '- Mobile-first media queries (min-width). Always use screen keyword.',
  '- Never nest beyond first level. No and operator except for media queries and parent-state.',
  '- Prefer stylesheet tag in sections/blocks for scoped CSS.',
  '',
  '### BEM Naming Convention',
  '- Block: component name (product-card)',
  '- Element: child of block (product-card__image)',
  '- Modifier: variant (product-card__image--rounded)',
  '- Use dashes between words within each segment',
  '- Examples: .hero-banner, .hero-banner__title, .hero-banner__title--large',
  '',
  '### Dawn CSS Custom Properties',
  '- --color-base, --color-foreground, --color-background (theming)',
  '- --font-body-family, --font-heading-family (typography)',
  '- --font-heading-scale, --font-body-scale (sizing via calc)',
  '- --page-width (container max-width)',
  '- --spacing-section (vertical rhythm)',
  '- Standard breakpoints: 750px, 990px, 1200px',
  '- Section padding: use .section--padding utility class',
  '- Container: .page-width with max-width: var(--page-width)',
  '',
  '### JavaScript Patterns',
  '- Zero dependencies: use native browser APIs first',
  '  - popover attribute, details element, IntersectionObserver, Fetch API',
  '- Variable declarations: const over let. Never var. Avoid mutation.',
  '- Iteration: for-of loops over forEach',
  '- Module pattern: classes with # private methods',
  '- Public API should be the smallest possible surface',
  '- Utility functions: module-scoped, not instance methods',
  '- Group scripts by feature area',
  '- Put blank lines before new blocks',
  '',
  '### JavaScript Class Pattern Example',
  'class ProductForm {',
  '  #cache = new Map();',
  '  addToCart(variantId) { this.#updateUI(variantId); }',
  '  #updateUI(id) { this.#cache.set(id, true); }',
  '}',
  'const formatPrice = (cents) => (cents / 100).toFixed(2);',
  '',
  '### Web Components in Themes',
  '- Use customElements.define for interactive elements',
  '- Extend HTMLElement, use connectedCallback/disconnectedCallback',
  '- Keep shadow DOM optional -- many themes use light DOM for CSS theming',
  '- Dispatch custom events for cross-component communication',
  '',
  '### Shopify-Specific JS Patterns',
  '- Variant selector: listen for change events on option inputs',
  '- Cart API: use Fetch to /cart/add.js, /cart/change.js, /cart/update.js',
  '- Section rendering API: ?sections=section-id for AJAX section updates',
  '- Theme editor events: subscribe to shopify:section:load, shopify:block:select',
  '- Product form: listen for variant:change custom event',
  '',
  '### Asset Loading',
  '- Critical CSS: inline in layout for above-fold content',
  '- Non-critical: use stylesheet_tag with media="print" onload pattern',
  '- Scripts: defer by default, async for independent scripts',
  '- Use javascript tag in sections for section-scoped deferred scripts',
  '',
  '### Shopify CSS Patterns (Few-Shot)',
  '  .product__info { padding: var(--spacing-section) 0 }',
  '  .product__title { font-size: var(--font-size-heading); margin-bottom: 1rem }',
  '  .price { color: rgb(var(--color-foreground)) }',
  '  .price--sale { color: rgb(var(--color-error)) }',
  '  .section--padding { padding-top: 2rem; padding-bottom: 2rem }',
  '  @media screen and (min-width: 750px) {',
  '    .section--padding { padding-top: 4rem; padding-bottom: 4rem }',
  '    .container { width: 100%; margin: 0 auto; padding: 0 1.5rem; max-width: var(--page-width) }',
  '  }',
  '  .card { border: 1px solid rgb(var(--color-border)); border-radius: var(--radius) }',
  '  .card__media { aspect-ratio: 1; overflow: hidden }',
  '  @media (prefers-reduced-motion: reduce) { .animate { animation: none } }',
  '',
  '### Shopify JS Patterns (Few-Shot)',
  '  // Product form → Cart API',
  '  const form = document.querySelector("[data-product-form]");',
  '  form?.addEventListener("submit", (e) => {',
  '    e.preventDefault();',
  '    fetch(window.Shopify.routes.root + "cart/add.js", { method: "POST", body: new FormData(form) });',
  '  });',
  '',
  '  // Variant picker with section ID',
  '  const sectionId = document.querySelector("[data-section-id]")?.dataset.sectionId;',
  '  document.querySelectorAll("[data-variant-option]").forEach((input) => {',
  '    input.addEventListener("change", () => updateVariant(sectionId, getSelectedOptions()));',
  '  });',
  '',
  '  // Cart drawer refresh',
  '  async function refreshCart() {',
  '    const res = await fetch(`${window.Shopify.routes.root}cart.js`);',
  '    const cart = await res.json();',
  '    document.querySelector("[data-cart-count]").textContent = cart.item_count;',
  '  }',
].join('\\n');

export const CSS_JS_STANDARDS_KEYWORDS = [
  'css', 'javascript', 'js', 'style', 'class', 'bem',
  'selector', 'specificity', 'important', 'variable', 'custom property',
  'media query', 'responsive', 'breakpoint', 'mobile',
  'dawn', 'convention', 'pattern', 'naming',
  'color', 'font', 'typography', 'spacing', 'padding',
  'script', 'module', 'class', 'private', 'const', 'let',
  'web component', 'custom element', 'shadow dom',
  'fetch', 'async', 'defer', 'lazy', 'critical css',
  'cart api', 'section rendering', 'variant selector',
  'design token', 'page-width', 'section--padding',
  'product form', 'cart drawer', 'data attribute', '.css', '.js',
];

export const CSS_JS_STANDARDS_TOKENS = 2200;
