/**
 * Knowledge module: Shopify Liquid objects -- global objects, product/variant model,
 * cart, customer, and request objects with key properties and access patterns.
 */

export const LIQUID_OBJECTS = [
  '## Liquid Objects Reference',
  '',
  '### Product Object',
  'product.title, product.description, product.handle, product.id',
  'product.price (current), product.compare_at_price (original), product.price_varies',
  'product.featured_image, product.images (array of Image objects)',
  'product.variants (array), product.selected_or_first_available_variant',
  'product.options (array of option names), product.options_with_values',
  'product.tags (array), product.type, product.vendor',
  'product.available, product.metafields.namespace.key',
  'product.url, product.template_suffix',
  'product.media (images + video + 3D models)',
  '',
  '### Variant Object',
  'variant.id, variant.title, variant.sku',
  'variant.price, variant.compare_at_price',
  'variant.available, variant.inventory_quantity',
  'variant.option1, variant.option2, variant.option3',
  'variant.image (variant-specific image)',
  'variant.url, variant.weight, variant.weight_unit',
  'variant.requires_shipping, variant.taxable',
  'variant.barcode, variant.metafields',
  '',
  '### Collection Object',
  'collection.title, collection.handle, collection.description',
  'collection.products (paginated), collection.products_count, collection.all_products_count',
  'collection.image, collection.url',
  'collection.sort_by, collection.default_sort_by',
  'collection.filters (array of FilterValue objects)',
  'collection.metafields.namespace.key',
  '',
  '### Cart Object',
  'cart.items (array of LineItem), cart.item_count',
  'cart.total_price, cart.total_weight',
  'cart.requires_shipping, cart.note',
  'cart.attributes, cart.currency',
  'cart.original_total_price, cart.total_discount',
  '',
  '### Line Item Object',
  'item.product, item.variant, item.title',
  'item.quantity, item.price, item.line_price',
  'item.original_price, item.original_line_price',
  'item.sku, item.url, item.image',
  'item.properties (custom line item properties)',
  '',
  '### Customer Object',
  'customer.first_name, customer.last_name, customer.name',
  'customer.email, customer.phone',
  'customer.orders (array), customer.orders_count, customer.total_spent',
  'customer.addresses, customer.default_address',
  'customer.tags (array), customer.accepts_marketing',
  'Access: wrap in if customer / endif conditional',
  '',
  '### Shop Object',
  'shop.name, shop.url, shop.domain, shop.permanent_domain',
  'shop.currency, shop.money_format, shop.money_with_currency_format',
  'shop.locale, shop.published_locales',
  'shop.metafields.namespace.key',
  '',
  '### Request / Page Context',
  'request.host, request.path, request.page_type',
  'request.locale (current), request.design_mode (true in theme editor)',
  'template.name (e.g. "product"), template.suffix',
  'canonical_url, page_title, page_description',
  '',
  '### Section / Block (Inside Sections)',
  'section.id, section.settings, section.blocks',
  'section.index (position in template)',
  'block.id, block.type, block.settings',
  'block.shopify_attributes (editor integration, output on wrapper)',
  '',
  '### Global Objects',
  'settings -- Theme-wide settings from settings_data.json',
  'routes -- Standard Shopify routes (routes.root_url, routes.cart_url, routes.account_url)',
  'content_for_header -- Required in layout head tag',
  'content_for_layout -- Required in layout body tag',
  'all_products["handle"] -- Access any product by handle',
  'collections["handle"] -- Access any collection by handle',
  'pages["handle"] -- Access any page by handle',
  'linklists["handle"] -- Access navigation menus',
  'blogs["handle"] -- Access blogs',
  'localization -- Available countries/languages',
  '',
  '### Metafields',
  'Access: product.metafields.namespace.key',
  'Types: single_line_text, multi_line_text, number_integer, number_decimal,',
  '  boolean, date, json, url, color, money, rating, dimension, weight, volume,',
  '  rich_text_field, file_reference, product_reference, collection_reference,',
  '  variant_reference, page_reference, list.*',
  'Render: product.metafields.custom.sizing | metafield_tag',
].join('\\n');

export const LIQUID_OBJECTS_KEYWORDS = [
  'product', 'variant', 'collection', 'cart', 'customer', 'shop',
  'request', 'section', 'block', 'settings', 'routes', 'metafield',
  'metafields', 'line_item', 'order', 'address', 'image', 'media',
  'option', 'options_with_values', 'selected_or_first_available',
  'featured_image', 'price', 'compare_at_price', 'available',
  'tags', 'vendor', 'type', 'handle', 'url', 'template',
  'content_for_header', 'content_for_layout', 'page_type',
  'design_mode', 'locale', 'localization', 'all_products',
  'linklists', 'canonical_url', 'page_title',
  'inventory_quantity', 'item_count', 'total_price',
  'money_format', 'sku', 'barcode', 'weight',
];

export const LIQUID_OBJECTS_TOKENS = 1800;
