/**
 * Knowledge module: Shopify Liquid core language -- schema format, 33 setting types,
 * LiquidDoc annotations, translation patterns, and template architecture.
 */

export const LIQUID_CORE = [
  '## Liquid Core: Schema, Settings, and Patterns',
  '',
  '### Section Schema Structure',
  'A section schema is a JSON block inside a Liquid file with these top-level keys:',
  '',
  '  name (string) -- Display name; use t: prefix for translation',
  '  tag (string) -- Wrapper HTML element (default: div)',
  '  class (string) -- CSS class on wrapper',
  '  limit (number) -- Max instances per page',
  '  settings (array) -- Section-level settings',
  '  blocks (array) -- Block type definitions, each with type/name/limit/settings',
  '  presets (array) -- Default configurations for "Add section"',
  '  max_blocks (number) -- Total block instances allowed (8-20 typical)',
  '  disabled_on / enabled_on -- Template/group restrictions',
  '',
  '### Setting Type Decision Table',
  '',
  '  Short text (title, label) --> text (single-line, 1-255 chars)',
  '  Long text (description) --> textarea (multi-line, plain text)',
  '  Formatted text (body copy) --> richtext (HTML output, toolbar)',
  '  Inline formatted text --> inline_richtext (no block elements)',
  '  Raw HTML --> html (XSS risk, limit use)',
  '  On/off toggle --> checkbox (boolean)',
  '  Numeric slider --> range (min/max/step/unit, great for spacing/opacity)',
  '  Number input --> number (arbitrary integer, no constraints)',
  '  Dropdown --> select (options[{value,label}], shows as segmented control if <=4)',
  '  Radio group --> radio (options[{value,label}], always visible)',
  '  Single image --> image_picker (returns media object, use image_url filter)',
  '  Video --> video (Shopify-hosted)',
  '  External video --> video_url (YouTube/Vimeo URL)',
  '  Color --> color (hex picker, returns hex string)',
  '  Gradient --> color_background (CSS gradient or solid color)',
  '  Font --> font_picker (Shopify font library)',
  '  URL --> url (any URL, with link picker)',
  '  Product ref --> product (returns product object)',
  '  Collection ref --> collection (returns collection object)',
  '  Blog ref --> blog (returns blog object)',
  '  Article ref --> article (returns article object)',
  '  Page ref --> page (returns page object)',
  '  Menu --> link_list (navigation menu handle)',
  '  Raw Liquid --> liquid (renders Liquid code from setting)',
  '  Section heading --> header (UI only -- groups settings visually)',
  '  Help text --> paragraph (UI only -- displays info text)',
  '',
  '### Block Best Practices',
  '- max_blocks: 8-20 for flexible sections, 1 for hero-style',
  '- limit on block types prevents merchant overuse of specific blocks',
  '- Order blocks logically: header > content > media > footer',
  '- Every block needs name (display) and type (lowercase, underscored)',
  '- Always output {{ block.shopify_attributes }} on the block wrapper div',
  '',
  '### Presets',
  '- At least one preset per section for theme editor "Add section"',
  '- Provide meaningful default settings and sample blocks',
  '- Preset name should be merchant-friendly, translatable via t: prefix',
  '',
  '### LiquidDoc (Section Documentation)',
  'Use doc/enddoc tags with @param annotations inside Liquid comments:',
  '  @param {String} heading - The section heading text',
  '  @param {Number} columns [3] - Number of grid columns (1-6)',
  '  @param {Boolean} show_border [false] - Show bottom border',
  '',
  '### Translation Patterns',
  '- Schema labels: "label": "t:sections.featured_collection.settings.heading.label"',
  '- Liquid output: use the | t filter on locale key strings',
  '- Pluralization: pass count variable to | t filter',
  '- Locale files: locales/en.default.json, locales/fr.json',
  '- Always use t: prefix in schema for translatable strings',
  '',
  '### Settings UX Guidelines',
  '- Order settings to match visual order (top-to-bottom, background-to-foreground)',
  '- Resource pickers first, then customization options',
  '- Group under header settings (Layout, Typography, Colors, Spacing)',
  '- Checkbox labels: nouns ("Language selector") not verbs ("Enable language selector")',
  '- Conditional settings: max 2 levels deep, code defensively -- hidden settings still evaluate',
  '- Always provide sensible default values for all settings',
].join('\\n');

export const LIQUID_CORE_KEYWORDS = [
  'schema', 'settings', 'blocks', 'presets', 'disabled_on', 'enabled_on',
  'section.settings', 'block.settings', 'max_blocks', 'setting type',
  'image_picker', 'color_background', 'font_picker', 'link_list',
  'liquiddoc', 'doc', 'param', 'translate', 'translation', 't:',
  'locale', 'locales', 'preset', 'shopify_attributes',
  'text', 'textarea', 'richtext', 'checkbox', 'range', 'select',
  'radio', 'color', 'url', 'number', 'video_url', 'html',
  'inline_richtext', 'header', 'paragraph', 'liquid',
];

export const LIQUID_CORE_TOKENS = 1800;
