/**
 * Knowledge module: Shopify Liquid filters -- complete reference organized by category.
 * Covers commerce, string, array, math, date, HTML/media, color, and money filters.
 */

export const LIQUID_FILTERS = [
  '## Liquid Filters Reference',
  '',
  '### Image and Media',
  '- | image_url: width: N -- Responsive image URL (preferred). Params: width, height, crop, format',
  '- | image_tag -- Generate img tag with srcset',
  '- | img_url: "WIDTHx" -- DEPRECATED, use image_url instead',
  '- | img_tag -- DEPRECATED, use image_tag instead',
  '- | media_tag -- Render media (image/video/3D model) with appropriate HTML',
  '- | external_video_tag -- Render YouTube/Vimeo embed',
  '- | video_tag -- Render Shopify-hosted video',
  '- | model_viewer_tag -- Render 3D model viewer',
  '- | placeholder_svg_tag -- SVG placeholder when no image assigned',
  '',
  '### Money and Commerce',
  '- | money -- Format with store currency symbol ($10.00)',
  '- | money_with_currency -- Format with currency code ($10.00 CAD)',
  '- | money_without_currency -- Format without symbol (10.00)',
  '- | money_without_trailing_zeros -- Drop .00 ($10)',
  '- | payment_button -- Render dynamic checkout button',
  '- | payment_type_img_url -- Payment icon URL',
  '- | payment_type_svg_tag -- Payment icon SVG',
  '',
  '### String',
  '- | append: str / | prepend: str -- Concatenate / prefix',
  '- | capitalize -- First letter uppercase',
  '- | upcase / | downcase -- Case conversion',
  '- | strip / | lstrip / | rstrip -- Whitespace trim',
  '- | strip_html -- Remove HTML tags',
  '- | strip_newlines -- Remove newlines',
  '- | newline_to_br -- Convert newlines to br tags',
  '- | replace: old, new / | replace_first: old, new -- String replace',
  '- | remove: str / | remove_first: str -- Remove substring',
  '- | truncate: N, "..." / | truncatewords: N -- Shorten text',
  '- | split: delimiter -- String to array',
  '- | escape / | escape_once -- HTML entity encoding',
  '- | url_encode / | url_decode -- URL encoding',
  '- | base64_encode / | base64_decode -- Base64',
  '- | md5 / | sha256 / | hmac_sha256 -- Hashing',
  '- | handleize / | handle -- URL-safe handle (my-product)',
  '- | pluralize: singular, plural -- Pluralization',
  '- | slice: start, length -- Substring',
  '',
  '### Array',
  '- | join: ", " -- Array to string',
  '- | first / | last -- First/last element',
  '- | size -- Count',
  '- | sort / | sort_natural -- Sort (case-sensitive / insensitive)',
  '- | reverse -- Reverse order',
  '- | map: "property" -- Extract property from objects',
  '- | where: "property", "value" -- Filter by property',
  '- | uniq -- Remove duplicates',
  '- | compact -- Remove nil values',
  '- | concat: array -- Merge arrays',
  '- | flatten -- Flatten nested arrays',
  '',
  '### Math',
  '- | plus: N / | minus: N -- Addition/subtraction',
  '- | times: N / | divided_by: N -- Multiplication/division',
  '- | modulo: N -- Remainder',
  '- | round / | ceil / | floor -- Rounding',
  '- | abs -- Absolute value',
  '- | at_most: N / | at_least: N -- Clamp value',
  '',
  '### Date',
  '- | date: "%B %d, %Y" -- Format date (strftime)',
  '- Common: %Y-%m-%d (2024-01-15), %B %d, %Y (January 15, 2024)',
  '- "now" | date: "%s" -- Current Unix timestamp',
  '',
  '### HTML and Asset',
  '- | asset_url -- URL for theme asset file',
  '- | file_url -- URL for Shopify Files (Settings > Files)',
  '- | stylesheet_tag -- Generate link CSS tag',
  '- | script_tag -- Generate script tag',
  '- | json -- Serialize to JSON (for JS data injection)',
  '- | default: value -- Fallback if nil/false/empty',
  '- | t -- Translation lookup from locale files',
  '- | t: count: N, name: str -- Translation with variables',
  '',
  '### Color',
  '- | color_to_rgb / | color_to_hsl / | color_to_hex -- Convert between formats',
  '- | color_modify: "alpha", 0.5 -- Modify channel',
  '- | color_lighten: 20 / | color_darken: 20 -- Adjust brightness',
  '- | color_saturate: 20 / | color_desaturate: 20 -- Adjust saturation',
  '- | color_brightness / | color_contrast: bg_color -- Accessibility checks',
  '- | color_mix: color2, weight -- Blend colors',
  '',
  '### Font',
  '- | font_face -- Generate @font-face CSS',
  '- | font_modify: "weight", "bold" -- Get font variant',
  '- | font_url -- Font file URL',
  '',
  '### Deprecated Filters (DO NOT USE)',
  '- | img_url --> use | image_url: width: N',
  '- | img_tag --> use | image_tag',
  '- | asset_img_url --> use | image_url on the asset',
  '- | product_img_url --> use | image_url on product.featured_image',
].join('\\n');

export const LIQUID_FILTERS_KEYWORDS = [
  'filter', 'image_url', 'img_url', 'money', 'money_with_currency',
  'asset_url', 'json', 'date', 'truncate', 'replace', 'append',
  'prepend', 'split', 'join', 'sort', 'where', 'map', 'first', 'last',
  'size', 'default', 'escape', 'strip_html', 'newline_to_br',
  'handleize', 'pluralize', 'color_to_rgb', 'font_face',
  'stylesheet_tag', 'script_tag', 'payment_button', 'url_encode',
  'base64', 'md5', 'sha256', 'slice', 'capitalize', 'upcase',
  'downcase', 'round', 'ceil', 'floor', 'abs', 'modulo',
  't', 'translate', 'image_tag', 'video_tag', 'media_tag',
  'color_modify', 'color_lighten', 'color_darken', 'color_contrast',
  'file_url', 'placeholder_svg',
];

export const LIQUID_FILTERS_TOKENS = 2000;
