/**
 * Knowledge module: Motion and animation system for Shopify themes.
 * Consolidates CSS @keyframes, Liquid data-animate patterns, JavaScript
 * IntersectionObserver recipes, and schema animation controls from the
 * V2 specialist agents (Liquid, CSS, JS).
 */

export const MOTION_PATTERNS = [
  '## Motion & Animation System for Shopify Sections',
  '',
  '### CSS @keyframes (include once per stylesheet)',
  '',
  '  @media (prefers-reduced-motion: no-preference) {',
  '    @keyframes fadeIn  { from { opacity: 0 } to { opacity: 1 } }',
  '    @keyframes slideUp { from { opacity: 0; transform: translateY(2rem) } to { opacity: 1; transform: translateY(0) } }',
  '    @keyframes scaleIn { from { opacity: 0; transform: scale(0.92) } to { opacity: 1; transform: scale(1) } }',
  '  }',
  '',
  '### Animation Triggers (tied to .is-visible from IntersectionObserver)',
  '',
  '  @media (prefers-reduced-motion: no-preference) {',
  '    [data-animate] { opacity: 0 }',
  '    [data-animate="fade"].is-visible  { animation: fadeIn 0.6s ease forwards }',
  '    [data-animate="slide"].is-visible { animation: slideUp 0.6s ease forwards }',
  '    [data-animate="scale"].is-visible { animation: scaleIn 0.5s ease forwards }',
  '  }',
  '',
  '### Staggered Children',
  '  @media (prefers-reduced-motion: no-preference) {',
  '    [data-animate].is-visible > *:nth-child(1) { animation-delay: 0s }',
  '    [data-animate].is-visible > *:nth-child(2) { animation-delay: 0.1s }',
  '    [data-animate].is-visible > *:nth-child(3) { animation-delay: 0.2s }',
  '    /* Continue as needed */',
  '  }',
  '',
  '### Hover Micro-Interactions',
  '  @media (prefers-reduced-motion: no-preference) {',
  '    .card { transition: transform 0.25s ease, box-shadow 0.25s ease }',
  '    .card:hover { transform: translateY(-3px) scale(1.015); box-shadow: 0 8px 24px oklch(0 0 0 / 0.12) }',
  '    .button { transition: transform 0.2s ease }',
  '    .button:hover { transform: scale(1.04) }',
  '  }',
  '',
  '### Liquid: data-animate Attributes',
  '  {%- if section.settings.enable_animations -%}',
  '    data-animate="{{ section.settings.animation_style }}"',
  '  {%- endif -%}',
  '',
  '### Liquid: Inline IntersectionObserver (bottom of section, before {% schema %})',
  '  <script>',
  '    (function () {',
  '      const els = document.querySelectorAll("[data-animate]");',
  '      if (!els.length) return;',
  '      const observer = new IntersectionObserver((entries) => {',
  '        entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("is-visible"); observer.unobserve(e.target); } });',
  '      }, { threshold: 0.15 });',
  '      els.forEach((el) => observer.observe(el));',
  '    })();',
  '  </script>',
  '',
  '### JavaScript: Standalone Observer (for theme JS asset)',
  '  function initScrollAnimations() {',
  '    const targets = document.querySelectorAll("[data-animate]");',
  '    if (!targets.length || !("IntersectionObserver" in window)) return;',
  '    const observer = new IntersectionObserver((entries) => {',
  '      entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("is-visible"); observer.unobserve(e.target); } });',
  '    }, { threshold: 0.15 });',
  '    targets.forEach((el) => observer.observe(el));',
  '  }',
  '  document.addEventListener("DOMContentLoaded", initScrollAnimations);',
  '  document.addEventListener("shopify:section:load", initScrollAnimations);',
  '',
  '### Schema Motion Controls (required in every new section)',
  '  { "type": "checkbox", "id": "enable_animations", "label": "Enable animations", "default": true },',
  '  { "type": "select", "id": "animation_style", "label": "Animation style",',
  '    "options": [{ "value": "fade", "label": "Fade in" }, { "value": "slide", "label": "Slide up" }, { "value": "scale", "label": "Scale in" }],',
  '    "default": "fade" }',
  '',
  '### Rules',
  '- ALL animation CSS must be inside @media (prefers-reduced-motion: no-preference)',
  '- unobserve after first intersection so animation fires once',
  '- Re-init on shopify:section:load for theme editor compatibility',
  '- Avoid duplicate observers: if section has inline <script>, skip theme JS observer',
  '- If user says "no animations", skip the entire motion pattern',
].join('\n');

export const MOTION_PATTERNS_KEYWORDS = [
  'animation', 'animate', 'motion', 'keyframes', 'fade', 'slide', 'scale',
  'hover', 'transition', 'scroll', 'reveal', 'stagger', 'data-animate',
  'intersection observer', 'is-visible', 'prefers-reduced-motion',
  'micro-interaction', 'scroll-triggered',
];

export const MOTION_PATTERNS_TOKENS = 1200;
