export interface LiquidFilterDefinition {
  name: string;
  inputType: string;
  outputType: string;
  description: string;
  shopifySpecific?: boolean;
}

export const STANDARD_FILTERS: LiquidFilterDefinition[] = [
  // ── String filters ──────────────────────────────────────────────────
  {
    name: "upcase",
    inputType: "string",
    outputType: "string",
    description: "Converts a string to uppercase",
  },
  {
    name: "downcase",
    inputType: "string",
    outputType: "string",
    description: "Converts a string to lowercase",
  },
  {
    name: "capitalize",
    inputType: "string",
    outputType: "string",
    description: "Capitalizes the first character of a string",
  },
  {
    name: "strip",
    inputType: "string",
    outputType: "string",
    description: "Strips leading and trailing whitespace from a string",
  },
  {
    name: "lstrip",
    inputType: "string",
    outputType: "string",
    description: "Strips leading whitespace from a string",
  },
  {
    name: "rstrip",
    inputType: "string",
    outputType: "string",
    description: "Strips trailing whitespace from a string",
  },
  {
    name: "strip_html",
    inputType: "string",
    outputType: "string",
    description: "Strips all HTML tags from a string",
  },
  {
    name: "strip_newlines",
    inputType: "string",
    outputType: "string",
    description: "Strips all newline characters from a string",
  },
  {
    name: "truncate",
    inputType: "string",
    outputType: "string",
    description: "Truncates a string to a given number of characters",
  },
  {
    name: "truncatewords",
    inputType: "string",
    outputType: "string",
    description: "Truncates a string to a given number of words",
  },
  {
    name: "replace",
    inputType: "string",
    outputType: "string",
    description: "Replaces all occurrences of a substring with another string",
  },
  {
    name: "remove",
    inputType: "string",
    outputType: "string",
    description: "Removes all occurrences of a substring from a string",
  },
  {
    name: "prepend",
    inputType: "string",
    outputType: "string",
    description: "Prepends a string to the beginning of another string",
  },
  {
    name: "append",
    inputType: "string",
    outputType: "string",
    description: "Appends a string to the end of another string",
  },
  {
    name: "split",
    inputType: "string",
    outputType: "array",
    description: "Splits a string into an array using a delimiter",
  },
  {
    name: "escape",
    inputType: "string",
    outputType: "string",
    description: "Escapes HTML entities in a string",
  },
  {
    name: "url_encode",
    inputType: "string",
    outputType: "string",
    description: "URL-encodes a string",
  },
  {
    name: "url_decode",
    inputType: "string",
    outputType: "string",
    description: "URL-decodes a string",
  },
  {
    name: "newline_to_br",
    inputType: "string",
    outputType: "string",
    description: "Converts newlines to HTML <br> tags",
  },

  // ── Number filters ──────────────────────────────────────────────────
  {
    name: "plus",
    inputType: "number",
    outputType: "number",
    description: "Adds a number to another number",
  },
  {
    name: "minus",
    inputType: "number",
    outputType: "number",
    description: "Subtracts a number from another number",
  },
  {
    name: "times",
    inputType: "number",
    outputType: "number",
    description: "Multiplies a number by another number",
  },
  {
    name: "divided_by",
    inputType: "number",
    outputType: "number",
    description: "Divides a number by another number",
  },
  {
    name: "modulo",
    inputType: "number",
    outputType: "number",
    description: "Returns the remainder of dividing a number by another number",
  },
  {
    name: "round",
    inputType: "number",
    outputType: "number",
    description: "Rounds a number to the nearest integer or specified decimal places",
  },
  {
    name: "ceil",
    inputType: "number",
    outputType: "number",
    description: "Rounds a number up to the nearest integer",
  },
  {
    name: "floor",
    inputType: "number",
    outputType: "number",
    description: "Rounds a number down to the nearest integer",
  },
  {
    name: "abs",
    inputType: "number",
    outputType: "number",
    description: "Returns the absolute value of a number",
  },

  // ── Array filters ───────────────────────────────────────────────────
  {
    name: "join",
    inputType: "array",
    outputType: "string",
    description: "Joins an array of strings with a delimiter",
  },
  {
    name: "first",
    inputType: "array",
    outputType: "any",
    description: "Returns the first element of an array",
  },
  {
    name: "last",
    inputType: "array",
    outputType: "any",
    description: "Returns the last element of an array",
  },
  {
    name: "size",
    inputType: "array",
    outputType: "number",
    description: "Returns the number of elements in an array or string",
  },
  {
    name: "map",
    inputType: "array",
    outputType: "array",
    description: "Extracts a property from each element of an array",
  },
  {
    name: "where",
    inputType: "array",
    outputType: "array",
    description: "Filters an array by a property value",
  },
  {
    name: "sort",
    inputType: "array",
    outputType: "array",
    description: "Sorts an array by a property or alphabetically",
  },
  {
    name: "reverse",
    inputType: "array",
    outputType: "array",
    description: "Reverses the order of elements in an array",
  },
  {
    name: "uniq",
    inputType: "array",
    outputType: "array",
    description: "Removes duplicate elements from an array",
  },
  {
    name: "concat",
    inputType: "array",
    outputType: "array",
    description: "Concatenates two arrays",
  },
  {
    name: "compact",
    inputType: "array",
    outputType: "array",
    description: "Removes nil values from an array",
  },

  // ── Shopify-specific filters ────────────────────────────────────────
  {
    name: "money",
    inputType: "number",
    outputType: "string",
    description: "Formats a price using the store's currency settings",
    shopifySpecific: true,
  },
  {
    name: "money_with_currency",
    inputType: "number",
    outputType: "string",
    description: "Formats a price with the currency code appended",
    shopifySpecific: true,
  },
  {
    name: "money_without_currency",
    inputType: "number",
    outputType: "string",
    description: "Formats a price without the currency symbol",
    shopifySpecific: true,
  },
  {
    name: "img_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL for an image with a given size",
    shopifySpecific: true,
  },
  {
    name: "asset_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL of a file in the assets folder",
    shopifySpecific: true,
  },
  {
    name: "asset_img_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL of an image in the assets folder with a given size",
    shopifySpecific: true,
  },
  {
    name: "product_img_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL of a product image with a given size",
    shopifySpecific: true,
  },
  {
    name: "file_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL of a file from the Files page of the admin",
    shopifySpecific: true,
  },
  {
    name: "shopify_asset_url",
    inputType: "string",
    outputType: "string",
    description: "Returns the URL of a global Shopify asset",
    shopifySpecific: true,
  },
  {
    name: "stylesheet_tag",
    inputType: "string",
    outputType: "string",
    description: "Generates an HTML <link> tag for a CSS stylesheet",
    shopifySpecific: true,
  },
  {
    name: "script_tag",
    inputType: "string",
    outputType: "string",
    description: "Generates an HTML <script> tag",
    shopifySpecific: true,
  },
  {
    name: "date",
    inputType: "string",
    outputType: "string",
    description: "Formats a date using strftime syntax",
    shopifySpecific: true,
  },
  {
    name: "pluralize",
    inputType: "number",
    outputType: "string",
    description: "Returns the singular or plural form based on a count",
    shopifySpecific: true,
  },
  {
    name: "json",
    inputType: "any",
    outputType: "string",
    description: "Converts a value to its JSON representation",
    shopifySpecific: true,
  },
  {
    name: "t",
    inputType: "string",
    outputType: "string",
    description: "Returns a translated string from the locale file",
    shopifySpecific: true,
  },
  {
    name: "link_to",
    inputType: "string",
    outputType: "string",
    description: "Generates an HTML <a> tag linking to a URL",
    shopifySpecific: true,
  },
  {
    name: "within",
    inputType: "string",
    outputType: "string",
    description: "Prepends a collection URL to a product URL for scoped navigation",
    shopifySpecific: true,
  },
  {
    name: "default",
    inputType: "any",
    outputType: "any",
    description: "Returns the given value unless it is blank, in which case returns a default",
    shopifySpecific: true,
  },
  {
    name: "color_to_rgb",
    inputType: "string",
    outputType: "string",
    description: "Converts a CSS color to RGB format",
    shopifySpecific: true,
  },
  {
    name: "color_to_hsl",
    inputType: "string",
    outputType: "string",
    description: "Converts a CSS color to HSL format",
    shopifySpecific: true,
  },
  {
    name: "color_lighten",
    inputType: "string",
    outputType: "string",
    description: "Lightens a CSS color by a given percentage",
    shopifySpecific: true,
  },
  {
    name: "color_darken",
    inputType: "string",
    outputType: "string",
    description: "Darkens a CSS color by a given percentage",
    shopifySpecific: true,
  },
];
